// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BFw9_-Q8QLPW8noyWqaefWq_g1Q-jug',
    appId: '1:924765570351:web:5f06668602da6defe3cdda',
    messagingSenderId: '924765570351',
    projectId: 'new-app-5b696',
    authDomain: 'new-app-5b696.firebaseapp.com',
    storageBucket: 'new-app-5b696.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3I1zhWBt1MbEbO4gHqQurKzwxfLVmks8',
    appId: '1:924765570351:android:4874d665693122b0e3cdda',
    messagingSenderId: '924765570351',
    projectId: 'new-app-5b696',
    storageBucket: 'new-app-5b696.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBClSzmFySrOuUFUBQTRPjSspd7dJU9cs4',
    appId: '1:924765570351:ios:ea08896146c3d2b1e3cdda',
    messagingSenderId: '924765570351',
    projectId: 'new-app-5b696',
    storageBucket: 'new-app-5b696.appspot.com',
    iosClientId: '924765570351-he4pi6tc6pviftf78rplgtm26hcce80r.apps.googleusercontent.com',
    iosBundleId: 'com.udesh.wings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBClSzmFySrOuUFUBQTRPjSspd7dJU9cs4',
    appId: '1:924765570351:ios:ea08896146c3d2b1e3cdda',
    messagingSenderId: '924765570351',
    projectId: 'new-app-5b696',
    storageBucket: 'new-app-5b696.appspot.com',
    iosClientId: '924765570351-he4pi6tc6pviftf78rplgtm26hcce80r.apps.googleusercontent.com',
    iosBundleId: 'com.udesh.wings',
  );
}
